export const TOGGLE_CART_MENU = `TOGGLE_CART_MENU`
export const SET_CART_ITEMS = `SET_CART_ITEMS`

export const FETCH_PRODUCTS_START = `FETCH_PRODUCTS_START`
export const FETCH_PRODUCTS_FAILED = `FETCH_PRODUCTS_FAILED`
export const FETCH_PRODUCTS_SUCCESS = `FETCH_PRODUCTS_SUCCESS`
